image_resolution: 224
# Rozdzielczość obrazu używana do przetwarzania i trenowania modelu. Wartość 224 jest standardowa dla wielu modeli sieci neuronowych.
data_directory: C:\Users\admin\Desktop\Praca Inżynierska\Dane\ODIR-5K
# Ścieżka do katalogu z danymi. Tutaj znajdują się obrazy dna oka, które będą używane do trenowania modelu
output_directory: C:\Users\admin\Desktop\Praca Inżynierska\Dane\ODIR-5K\experiments
# Ścieżka do katalogu, w którym będą zapisywane wyniki eksperymentów, takie jak modele, wykresy i inne artefakty.
experiment_name: test
# Nazwa bieżącego eksperymentu. Przydatne do organizacji wyników, szczególnie gdy przeprowadza się wiele eksperymentów.
images_path: "preprocessed_images"
# Ścieżka względna lub nazwa katalogu, w którym znajdują się przetworzone obrazy. Przydatne, gdy obrazy muszą zostać wstępnie przetworzone przed treningiem.
metadata_file_name: "full_df.csv"
# Nazwa pliku CSV zawierającego metadane związane z obrazami. Plik ten może zawierać etykiety, identyfikatory pacjentów, dodatkowe cechy itp.
epochs: 1 # TODO change to 100
# Liczba epok, przez które model będzie trenowany. Obecnie ustawione na 1 dla testów, ale docelowo należy zmienić na większą liczbę, np. 100.
batch_size: 2
# Rozmiar partii (batch size) używany podczas trenowania modelu. Określa, ile próbek będzie przetwarzanych jednocześnie.
shuffling_buffer: 10 # TODO change to a greater number
# Rozmiar bufora używanego do mieszania danych przed podaniem ich do modelu. Obecnie ustawione na 10, ale warto zwiększyć dla lepszej losowości.
decision_class: "A"
# Klasa decyzyjna, na której model się skupia. Może być to etykieta klasyfikacji, np. "A" dla jaskry.
seed: 421
# Losowe ziarno używane do inicjalizacji generatorów losowych. Umożliwia powtarzalność wyników eksperymentów