image_resolution: 224
data_directory: C:\Users\admin\Desktop\Praca Inżynierska\Dane\ODIR-5K
output_directory: C:\Users\admin\Desktop\Praca Inżynierska\Dane\ODIR-5K\experiments
experiment_name: test
images_path: "preprocessed_images"
metadata_file_name: "full_df.csv"
epochs: 1 # TODO change to 100
batch_size: 2
shuffling_buffer: 10 # TODO change to a greater number
decision_class: "A"
seed: 421